"use client";

import React from "react";
import { useGLTF } from "@react-three/drei";

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

export function Brain(props) {
  const { nodes, materials } = useGLTF("/brain.gltf");

  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials["Scene_-_Root"]} />
        <mesh geometry={nodes.Object_3.geometry} material={materials["Scene_-_Root"]} />
        <mesh geometry={nodes.Object_4.geometry} material={materials["Scene_-_Root"]} />
        <mesh geometry={nodes.Object_5.geometry} material={materials["Scene_-_Root"]} />
      </group>
    </group>
  );
}

useGLTF.preload("/brain.gltf");